### PR TITLE
Use boost 1.49.0 on kesch

### PR DESCRIPTION
**Pull request by havogt**
It seems like the stella debug plan doesn't compile with 1.67.0

### CODE REVIEW

**Comment by havogt** [comment]
(installation is currently in progress)

**Comment by havogt** [comment]
Compilation failed, so not installed yet. Do we need compiled libraries or just the headers?

**Comment by havogt** [comment]
Probably no one cares about that anymore. I don't remember it...
